## Simple single layer neural network

In [19]:
import numpy as np                          #import dependencies for matrix math

input data | output label
---------- | ------------
0 0 1 | 0
0 0 1 | 1
1 0 1 | 1
1 1 1 | 0

In [36]:
# input data
input_data = np.array([[0,0,1],                   
                       [0,0,1],
                       [1,0,1],
                       [1,1,1]])            # input array (4x3)
output_label = np.array([[0],
                         [1],
                         [1],
                         [0]])              # output label or array (4x1)
print(input_data,' = input data\n')         # display input data
print(output_label,' = output label\n')     # display output label(data)

[[0 0 1]
 [0 0 1]
 [1 0 1]
 [1 1 1]]  = input data

[[0]
 [1]
 [1]
 [0]]  = output label



### Sigmoid function 
$$
f(x) = \frac{1}{(1+e^{-x})}
$$

In [37]:
# sigmoid function 

def activate(x,deriv=False):
    if deriv == True:
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [38]:
# weights

synaptic_weights = 2 * np.random.random((3,1)) - 1   # assign random numbers to weight array
print(synaptic_weights,' = weights\n')               # display weights 

[[ 0.80786993]
 [-0.80907164]
 [ 0.33297204]]  = weights



In [48]:
# training 
for iteration in range(10000):
    output = activate(np.dot(input_data,synaptic_weights))                 # (4x3) x (3x1)
    error = output_label - output                                          # (4x1) - (4x1)
    synaptic_weights += np.dot(input_data.T, error * activate(output,True))# (4x3)T x ((4x1) . (4x1))

In [50]:
# test for (1,1,0)
test = activate(np.dot(np.array([1,1,0]),synaptic_weights))
print(test)                                            # display answer

[ 0.0070069]
