## Basic neural network #1

In [1]:
import numpy as np

#### Sigmoid function
$$
    f(x) = \frac{1}{1+e^{-x}}
$$

In [2]:
def sigmoid(x,deriv=False):
    if(deriv == True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [3]:
X = np.array([[0,0,1],
                      [0,1,1],
                      [1,0,1],
                      [1,1,1]])
y = np.array([[0],
                        [1],
                        [1],
                        [0]])
print(X,' = input data\n')

print(y,' = outpu label\n')

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]  = input data

[[0]
 [1]
 [1]
 [0]]  = outpu label



In [4]:
np.random.seed(1)

#synapsis
syn0 = 2 * np.random.random((3,4)) - 1
syn1 = 2 * np.random.random((4,1)) - 1
print(syn0,'\n\n',syn1)

[[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]] 

 [[-0.5910955 ]
 [ 0.75623487]
 [-0.94522481]
 [ 0.34093502]]


In [5]:
for i in range(60000):
    l0 = X                         # first layer (input layer)
    l1 = sigmoid(np.dot(l0,syn0))  # layer 2 
    l2 = sigmoid(np.dot(l1,syn1))  # layer 3
    
    l2_error = y - l2              # find error
    
    if(i % 10000) == 0:
        print('error:',str(np.mean(np.abs(l2_error))))
    
    l2_delta = l2_error * sigmoid(l2,deriv=True)
    l1_error = l2_delta.dot(syn1.T)
    
    l1_delta = l1_error * sigmoid(l1,deriv=True)
    
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)

error: 0.496410031903
error: 0.00858452565325
error: 0.00578945986251
error: 0.00462917677677
error: 0.00395876528027
error: 0.00351012256786


In [6]:
print("output after training")
print(l2)

output after training
[[ 0.00260572]
 [ 0.99672209]
 [ 0.99701711]
 [ 0.00386759]]


In [ ]:
    l0 = X                         # first layer (input layer)
    l1 = sigmoid(np.dot(l0,syn0))  # layer 2 
    l2 = sigmoid(np.dot(l1,syn1))  # layer 3
    
    l2_error = y - l2              # find error
    
    if(i % 10000) == 0:
        print('error:',str(np.mean(np.abs(l2_error))))
    
    l2_delta = l2_error * sigmoid(l2,deriv=True)
    l1_error = l2_delta.dot(syn1.T)
    
    l1_delta = l1_error * sigmoid(l1,deriv=True)
    
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)

In [ ]:
print(l0,'\n',l1,'\n',l2)

In [ ]:
print(l2_error,'\n\n',l2,'\n\n',l2_delta)

In [ ]:
print(l1_error.shape, l2_delta.shape, syn1.shape)
print('\n\n',l1_error,'\n\n', l2_delta,'\n\n', syn1)

In [ ]:
print(l1_delta.shape,l1_error.shape,l1.shape)