In [1]:
import numpy as np    #import dependencies for matrix math

In [2]:
# input data
input_data = np.array([[0,0,1],
                      [0,0,1],
                      [1,0,1],
                      [1,1,1]])
output_label = np.array([[0],
                        [1],
                        [1],
                        [0]])
print(input_data,' = input data\n')
print(output_label,' = outpu label\n')

[[0 0 1]
 [0 0 1]
 [1 0 1]
 [1 1 1]]  = input data

[[0]
 [1]
 [1]
 [0]]  = outpu label



In [3]:
def change(x):
    if x >= .5:
        return 1
    return 0

In [4]:
# sigmoid function
def activate(x,deriv=False):
    if deriv == True:
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [6]:
# weight values
synaptic_weight  = 2 * np.random.random((3,1)) -1

print(synaptic_weight,' = weights\n')

[[ 0.39415486]
 [-0.34221746]
 [ 0.00513788]]  = weights



In [7]:
print(activate(np.dot(input_data,synaptic_weight),' = random guess answer'))

[[ 0.50128447]
 [ 0.50128447]
 [ 0.59851772]
 [ 0.51426495]]


In [8]:
# training

for iteration in range(1000):
    output = activate(np.dot(input_data,synaptic_weight))
    error = output_label - output
    synaptic_weight += np.dot(input_data.T, error * activate(output,True))


In [9]:
print(error,' = error')

[[-0.50114881]
 [ 0.49885119]
 [ 0.04198429]
 [-0.03403907]]  = error


In [13]:
# test 
test1 = activate(np.dot(np.array([0,0,0]),synaptic_weight))
test2 = activate(np.dot(np.array([1,1,0]),synaptic_weight))
test3 = activate(np.dot(np.array([1,1,1]),synaptic_weight))
print((test1))
print((test2))
print(test3)

[ 0.5]
[ 0.0338703]
[ 0.03402083]


In [11]:
print(input_data.shape)
print(error.shape)
print(output.shape)

(4, 3)
(4, 1)
(4, 1)
