In [1]:
import numpy as np    #import dependencies for matrix math

In [3]:
# input data
input_data = np.array([[0,0,1],
                      [0,1,1],
                      [1,0,1],
                      [1,1,1]])
output_label = np.array([[0],
                        [1],
                        [1],
                        [0]])
print(input_data,' = input data\n')
print(output_label,' = outpu label\n')

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]  = input data

[[0]
 [1]
 [1]
 [0]]  = outpu label



In [4]:
def change(x):
    if x >= .5:
        return 1
    return 0

In [5]:
# sigmoid function
def activate(x,deriv=False):
    if deriv == True:
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [13]:
# weight values
synaptic_weight_0 = 2 * np.random.random((3,4)) - 1
synaptic_weight_1 = 2 * np.random.random((4,1)) - 1 

print(synaptic_weight_0,' = weights1\n')
print(synaptic_weight_1,' = weights2\n')

[[ 0.00941113  0.09034493  0.6813381  -0.7563857 ]
 [-0.727694    0.72732278 -0.00089157 -0.33585983]
 [-0.69307991 -0.1958491  -0.60772285 -0.19114341]]  = weights1

[[ 0.77883008]
 [-0.35895589]
 [-0.23349672]
 [ 0.39722945]]  = weights2



In [7]:
print(activate(np.dot(input_data,synaptic_weight),' = random guess answer'))

[[ 0.28646193]
 [ 0.25927496]
 [ 0.14958527]
 [ 0.13296796]]


In [15]:
# training

for iteration in range(60000):
    layer0 = input_data
    layer1 = activate(np.dot(layer0,synaptic_weight_0))
    layer2 = activate(np.dot(layer1,synaptic_weight_1))
    
    layer2_error = output_label - layer2
    
    if (iteration% 10000) == 0:
        print("error:",str(np.mean(np.abs(layer2_error))))
    
    layer2_gradient = layer2_error * activate(layer2,deriv=True)
    
    layer1_error = layer2_gradient.dot(synaptic_weight_1.T)
    
    layer1_gradient = layer1_error * activate(layer1,deriv=True)
    
    
    synaptic_weight_0 += layer1.T.dot(layer2_gradient)
    synaptic_weight_1 += layer0.T.dot(layer1_gradient)


error: 0.500444782176


ValueError: operands could not be broadcast together with shapes (3,4) (4,1) (3,4) 

In [18]:
for j in range(60000):

	# Forward propagate through layers 0, 1, and 2
    layer0 = input_data
    layer1 = activate(np.dot(layer0,synaptic_weight_0))
    layer2 = activate(np.dot(layer1,synaptic_weight_1))

    #calculate error for layer 2
    layer2_error = output_label - layer2
    
    if (j% 10000) == 0:
        print("Error:" + str(np.mean(np.abs(layer2_error))))
        
    #Use it to compute the gradient
    layer2_gradient = layer2_error*activate(layer2, deriv=True)

    #calculate error for layer 1
    layer1_error = layer2_gradient.dot(synaptic_weight_1.T)
    
    #Use it to compute its gradient
    layer1_gradient = layer1_error * activate(layer1,deriv=True)
    
    #update the weights using the gradients
    synaptic_weight_1 += layer1.T.dot(layer2_gradient)
    synaptic_weight_0 += layer0.T.dot(layer1_gradient)


Error:0.500444782176
Error:0.0100824812387
Error:0.00686335661501
Error:0.00550829868965
Error:0.0047200737646
Error:0.00419041478722


In [19]:
print(error,' = error')

[[-0.5]
 [ 0.5]
 [ 0.5]
 [-0.5]]  = error


In [20]:
# test 
test1 = activate(np.dot(np.array([0,0,0]),synaptic_weight))
test2 = activate(np.dot(np.array([1,1,0]),synaptic_weight))
test3 = activate(np.dot(np.array([1,1,1]),synaptic_weight))
print((test1))
print((test2))
print(test3)

[ 0.5]
[ 0.5]
[ 0.5]


In [21]:
print(input_data.shape)
print(error.shape)
print(output.shape)

(4, 3)
(4, 1)
(4, 1)
